### ISSUE TITLE
Can you provide the code for ensemble mlp?

### ISSUE THREAD

**Issue by zivlumous** [Juanhui28/Are_MPNNs_helpful#1]

**Comment by Juanhui28** [comment]
Hi there, thanks for the interest. I upload some files about the ensemble: https://github.com/Juanhui28/Are_MPNNs_helpful/blob/main/Readme_ensemble.md.

We apology that the code cannot run since we didn't save the trained models and some files were deleted. But we still want to provide some details of how we do the ensemble. Sorry for the inconvenience.
